resolver: nightly-2019-03-14

flags:
  Taiji-scRNA-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-types.git
  commit:  27fbb517f6b334a48300f01aa925011fee849547

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  94c3de1a5e13e048d7cc5d53cc0295ca395ac1e7

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  4e8dfffd751229259e6e3cede1483fb7fe7bf018

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  4c425bf96f392fb1f9098821f643895ef1226151

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- bioinformatics-toolkit-0.7.0
- HsHTSLib-1.9.2
- drmaa-0.2.0
- clustering-0.4.1
- SciFlow-0.6.2