resolver: nightly-2019-05-25

flags:
  Taiji-scRNA-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  d74b455b0eac235b1059c5dee50ec5d960a6608b

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  ed1aba1edb923ae61b4e2b2ee2b2a60e7c2be86c

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  f5eb179697a15515786a03ee1fad5fe5bcfd4a00

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  470d1c09c8b8ecc64ced5f085c87cc66d70f8b9d

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  92a77e51d23bdb10b72bf21139468e2b6d45a335
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-drmaa
- drmaa-0.3.0
- distributed-process-monad-control-0.5.1.3
- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  b7591922edafb0203d8ef4c39a724ff0553327da
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  d58250e2388b86a1865ac4139373cbdc106e72e1
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14

- bioinformatics-toolkit-0.9.0
- HsHTSLib-1.9.2
- clustering-0.4.1